### PR TITLE
add line 17

### PR DESCRIPTION
**Pull request by Larionovv**

### CODE REVIEW

**Review by vitaliy-tkachuk — APPROVED** [review]
Good job!

**Review by vitaliy-tkachuk — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved

**Review by da411d — APPROVED** [review]
Ахахха прочитав "похавайте і вставайте"😅

**Review by mishalisovskiy — APPROVED** [review]

**Review by ghost — APPROVED** [review]
👍

**Review by vitaliy-tkachuk — APPROVED** [review]

**Pull request merged**
